In [1]:
# multiply two matrix using list comprehension
x = [[1,7,3],
     [3,5,6],
     [6,8,9]]
y = [[1,1,1,2],
     [6,7,3,0],
     [4,5,9,1]]

In [4]:
# result will be 3*4 matrix
result = [[sum(x*y for x,y in zip(X_row, Y_col))
                        for Y_col in zip(*y)]
                                for X_row in x]
for r in result:
    print(r)

[55, 65, 49, 5]
[57, 68, 72, 12]
[90, 107, 111, 21]


In [6]:
#program to multiply two matrix(vectorized implementation)

import numpy as np

A=[[12,7,3],
   [4,5,6],
   [7,8,9]]

B=[[5,8,1,2],
   [6,7,3,0],
   [4,5,59,1]]

#result will be 3*4

result=[[0,0,0,0],
        [0,0,0,0],
        [0,0,0,0]]

result = np.dot(A,B)

for r in result:
    print(r)
A=[[5,8,1,2],
   [6,7,3,0],
   [4,5,59,1]]


[114 160 210  27]
[ 74  97 373  14]
[119 157 562  23]
